/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GestorParque;

import java.sql.Date;
import java.util.List;

public class App {
   public static void main(String[] args) {
        Parque parque = new Parque();

        // Adicionar uma atração
        Atracao montanhaRussa = new Atracao(0, "Montanha Russa", 20, 30);
        parque.adicionarAtracao(montanhaRussa);

        // Adicionar um visitante
        Visitante visitante1 = new Visitante(0, "João", 25, 1.75, "Aventuras");
        parque.adicionarVisitante(visitante1);

        // Adicionar um ingresso
        Ingresso ingresso1 = new Ingresso(0, new Date(System.currentTimeMillis()), "Inteira", 50.0);

        // Adicionar uma venda
        Venda venda1 = new Venda(0, ingresso1, visitante1, montanhaRussa);
        parque.adicionarVenda(venda1);

        // Listar atrações
        List<Atracao> atracoes = parque.listarAtracoes();
        for (Atracao atracao : atracoes) {
            System.out.println("Atração: " + atracao.getNome());
        }

        // Listar visitantes
        List<Visitante> visitantes = parque.listarVisitantes();
        for (Visitante visitante : visitantes) {
            System.out.println("Visitante: " + visitante.getNome());
        }

        // Listar vendas
        List<Venda> vendas = parque.listarVendas();
        for (Venda venda : vendas) {
            System.out.println("Venda: Ingresso ID - " + venda.getIngresso().getId() + ", Visitante - " + venda.getVisitante().getNome() + ", Atração - " + venda.getAtracao().getNome());
        }
    }
}
